from datetime import datetime, timezone
from sqlalchemy import (
    Column,
    DateTime,
    ForeignKey,
    Integer,
    JSON,
    String,
    Text,
)
from sqlalchemy.orm import relationship
from app.database import Base


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


class Project(Base):
    __tablename__ = "projects"

    id = Column(Integer, primary_key=True, index=True)

    name = Column(
        String(255),
        nullable=False,
    )

    repo_url = Column(
        String(500),
        nullable=False,
    )

    owner = Column(
        String(255),
        nullable=False,
    )

    repo = Column(
        String(255),
        nullable=False,
    )

    created_at = Column(
        DateTime(timezone=True),
        default=utc_now,
        nullable=False,
    )

    members = relationship(
        "Member",
        back_populates="project",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    events = relationship(
        "Event",
        back_populates="project",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    tasks = relationship(
        "Task",
        back_populates="project",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    analyses = relationship(
        "AnalysisResult",
        back_populates="project",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    understanding_sessions = relationship(
        "UnderstandingSession",
        back_populates="project",
        cascade="all, delete-orphan",
        lazy="selectin",
    )


class Member(Base):
    __tablename__ = "members"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    project_id = Column(
        Integer,
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    member_number = Column(
        Integer,
        nullable=False,
    )

    github_username = Column(
        String(255),
        nullable=True,
        index=True,
    )

    display_name = Column(
        String(255),
        nullable=False,
    )

    github_contributions = Column(
        Integer,
        nullable=True,
    )

    project = relationship(
        "Project",
        back_populates="members",
    )

    events = relationship(
        "Event",
        back_populates="member",
        lazy="selectin",
    )

    understanding_sessions = relationship(
        "UnderstandingSession",
        back_populates="member",
        cascade="all, delete-orphan",
        lazy="selectin",
    )


class Event(Base):
    __tablename__ = "events"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    project_id = Column(
        Integer,
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    member_id = Column(
        Integer,
        ForeignKey("members.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Examples:
    # COMMIT
    # PR_CREATED
    # PR_MERGED
    # REVIEW
    # REVIEW_COMMENT
    # PR_COMMIT
    # ISSUE_CREATED
    # ISSUE_COMMENT
    # CI_RUN
    # BRANCH_CREATED
    event_type = Column(
        String(50),
        nullable=False,
    )

    timestamp = Column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
    )

    source_id = Column(
        String(255),
        nullable=False,
    )

    artifact = Column(
        String(500),
        nullable=True,
    )

    # We intentionally store normalized useful GitHub information
    # instead of complete raw GitHub responses.
    metadata_json = Column(
        JSON,
        nullable=True,
    )

    project = relationship(
        "Project",
        back_populates="events",
    )

    member = relationship(
        "Member",
        back_populates="events",
    )


class Task(Base):
    __tablename__ = "tasks"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    project_id = Column(
        Integer,
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    name = Column(
        String(255),
        nullable=False,
    )

    description = Column(
        Text,
        nullable=True,
    )

    file_patterns = Column(
        JSON,
        nullable=True,
        default=list,
    )

    # manual -> professor/user created
    # llm    -> generated by LLM
    # auto   -> deterministic discovery
    source = Column(
        String(50),
        nullable=False,
        default="manual",
    )

    project = relationship(
        "Project",
        back_populates="tasks",
    )


class AnalysisResult(Base):
    __tablename__ = "analysis_results"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    project_id = Column(
        Integer,
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    created_at = Column(
        DateTime(timezone=True),
        default=utc_now,
        nullable=False,
    )

    analysis_json = Column(
        JSON,
        nullable=False,
    )

    project = relationship(
        "Project",
        back_populates="analyses",
    )


class UnderstandingSession(Base):
    __tablename__ = "understanding_sessions"

    id = Column(Integer,primary_key=True,index=True)
    project_id = Column(
        Integer,
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    member_id = Column(
        Integer,
        ForeignKey("members.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    created_at = Column(
        DateTime(timezone=True),
        default=utc_now,
        nullable=False,
    )

    completed_at = Column(
        DateTime(timezone=True),
        nullable=True,
    )

    status = Column(
        String(50),
        nullable=False,
        default="QUESTIONS_GENERATED",
    )
    questions_json = Column(
        JSON,
        nullable=False,
        default=dict,
    )

    answers_json = Column(
        JSON,
        nullable=True,
        default=dict,
    )
    evaluation_json = Column(
        JSON,
        nullable=True,
    )

    understanding_score = Column(
        Integer,
        nullable=True,
    )

    project = relationship(
        "Project",
        back_populates="understanding_sessions",
    )

    member = relationship(
        "Member",
        back_populates="understanding_sessions",
    )